title: aptdekho
description: Whiptail menu type for APT package manager.
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - LICENSE.md
  - README.md
  - article.md
